FROM node:10.15.3
EXPOSE 4200

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY ./DreamFrontEnd/package.json /app/package.json

RUN npm install
RUN npm install -g @angular/cli@6.2.4

COPY ./DreamFrontEnd /app

CMD ["ng", "serve", "--host 0.0.0.0", "--port 4200"]