FROM openjdk:8
ADD target/trading-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'echo spring.datasource.url=jdbc:mysql://localhost:3306/pillowcase > application.properties'
RUN sh -c 'echo spring.datasource.username=root >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre >> application.properties'
RUN sh -c 'echo spring.datasource.driverClassName=com.mysql.jdbc.Driver >> application.properties'
RUN sh -c 'echo server.port=8081 >> application.properties'
RUN sh -c 'echo logging.level.root=ERROR >> application.properties'
RUN sh -c 'echo spring.activemq.packages.trust-all=true >> application.properties'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]