version: '3.0'
services:
   mysql:
      container_name: mysql
      build:
        context: .
        dockerfile: Dockerfile-mysql
      image: dt/mysql:1.0.0
      ports:
        - "3306:3306"
      volumes:
        - /docker/dt/mysql:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: c0nygre
      command: --explicit_defaults_for_timestamp
  dt:
    container_name: spring
      build:
        context: .
        dockerfile: Dockerfile-spring
      image: dt/spring:1.0.0
      links:
        - mysql:mysql
      ports:
        - "8080:8081"
      restart: always

  angular:
    container_name: angular
      build:
        context: .
        dockerfile: Dockerfile-angular
      image: dt/angular:1.0.0
      ports:
        - "80:4200"
      restart: always