FROM openjdk:8
ADD ./DreamBackEnd/target/trading-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'echo spring.datasource.url=jdbc:mysql://localhost:3306/dreamcatcher > ./DreamBackEnd/application.properties'
RUN sh -c 'echo spring.datasource.username=root >> ./DreamBackEnd/application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre >> ./DreamBackEnd/application.properties'
RUN sh -c 'echo spring.datasource.driverClassName=com.mysql.jdbc.Driver >> ./DreamBackEnd/application.properties'
RUN sh -c 'echo server.port=8081 >> ./DreamBackEnd/application.properties'
RUN sh -c 'echo logging.level.root=ERROR >> ./DreamBackEnd/application.properties'
RUN sh -c 'echo spring.activemq.packages.trust-all=true >> ./DreamBackEnd/application.properties'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]