FROM openjdk:8
ADD ./DreamBackEnd/target/trading-1.0-SNAPSHOT.jar app.jar
RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/dreamcatcher > application.properties'
RUN sh -c 'echo spring.datasource.username=root >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre >> application.properties'
RUN sh -c 'echo logging.level.root=ERROR >> application.properties'
RUN sh -c 'echo spring.activemq.packages.trust-all=true >> application.properties'
EXPOSE 8080
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]